language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

script:
  - composer tests

install:
  - travis_retry composer install --no-interaction --prefer-source
