name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        php: ['7.4', '8.0', '8.1', '8.2']
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        if: ${{ matrix.php != '8.2' }}
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: composer update --no-interaction --no-progress

      - name: Install Dependencies (ignore platform)
        if: ${{ matrix.php == '8.2' }}
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: composer update --no-interaction --no-progress --ignore-platform-req=php

      - name: Run QA checks
        run: composer run-script qa
        env:
          PHP_CS_FIXER_IGNORE_ENV: 1
